import time
import numpy as np

def maintest(settings, test_series, plot_function, *args, **kwargs):
    # Count up from 1 to 5
    raise Exception("This is the exception encounterd in the test!")
    return "pass"